### ISSUE TITLE
[ML] 비지도학습 관련 조사 및 ppt 레이아웃 구성

### ISSUE THREAD

**Issue by yewon126** [hurontrara/hufs-ml-mlserver#12]
## 기능 설명

- ppt 레이아웃
- 비지도 학습 타당성 평가 방법 조사
- 비지도 학습 시각화 방법 조사

## 구현 방법

- 레퍼런스 참고 조사

## 타임 라인

- 11/24 ~ 12/1

## 비고

<br>

**Comment by hurontrara** [comment]
프로젝트 종료에 따른 이슈 종료
