### ISSUE TITLE
[ML] 비지도학습 기법 선택 및 최적화 

### ISSUE THREAD

**Issue by er1123090hufs** [hurontrara/hufs-ml-mlserver#13]
## 기능 설명

- 비지도학습을 통한 최적화 clustering 

## 구현 방법

- domain에 가장 적합한 비지도학습 알고리즘 선택
- 적절한 clustering 값 설정
- PCA를 통한 벡터 차원 축소 

## 타임라인
2024.11.24 ~ 2024.12.1

## 비고
 [ML] 최적 비지도학습 모델 구현 

<br>

**Comment by hurontrara** [comment]
프로젝트 종료에 따른 이슈 종료
