### ISSUE TITLE
[ML] 군집 시각화 방법 및 API 설계 방식 조사

### ISSUE THREAD

**Issue by YangEonPil** [hurontrara/hufs-ml-mlserver#14]
## 기능 설명

- 군집 시각화, 특히 고차원 시각화 방법 조사 

- API 설계 및 REST API 설계 

- 설계에 사용한 비지도학습 타당성 평가 방법 구체화 

## 구현 방법

- 회의 참관, 자료조사, 질의 

## 타임 라인

- 2023-12-01

## 비고

구체적 구현 방식에 중점 

<br>

**Comment by hurontrara** [comment]
프로젝트 종료에 따른 이슈 종료
