### ISSUE TITLE
[ML] 11월  3주차에 해야할 것들

### ISSUE THREAD

**Issue by ParkWonjeong** [hurontrara/hufs-ml-mlserver#8]
## 기능 설명

- flask 기본 개념 더 공부
- REST API 서버 배포 공부

## 구현 방법

- 유튜브로 보고 실습하기
- 문서도 찾아보기

## 타임 라인

- 2023-11-17 ~ 2023-11-24

## 비고

<br>

**Comment by hurontrara** [comment]
시간 되시면, CI/CD 도 알아보시고 적용하시면 좋을 것 같습니다!

인프라 이해하시는데 도움이 많이 될거에요!

**Comment by ParkWonjeong** [comment]
더 열심히 해보겠습니다~!
